name: Docker Build and Push
on:
  push:
    branches:
      - main
jobs:
  docker_build_and_push:
    runs-on: ubuntu-latest
    outputs:
      docker_tag_date: ${{ steps.set_env.outputs.DOCKER_TAG_DATE }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set current date as environment variable
        run: echo "DOCKER_TAG_DATE=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/currencyconverter:${{ needs.docker_build_and_push.outputs.docker_tag_date }}
  
  deploy_to_kubernetes:
    needs: docker_build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
          location: ${{ secrets.GKE_CLUSTER_LOCATION }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - name: Update deployment image
        run: |
          kubectl set image deployment/my-app-deployment my-app-container=${{ secrets.DOCKER_HUB_USERNAME }}/currencyconverter:${{ env.DOCKER_TAG_DATE }}

      - name: Verify deployment
        run: |
          kubectl rollout status deployment/my-app-deployment
